---
apiVersion: batch/v1
kind: Job
metadata:
  name: open-head-{id}
  namespace: hydra-doom
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: "open-head"
          image: "ghcr.io/demeter-run/hydra-control-plane-open-head:rc2"
          command: ["sh", "/etc/script/open-head.sh"]
          env:
            - name: BLOCKFROST_KEY
              value: "{blockfrost_key}"
            - name: ADDRESS
              value: "addr_test1vpgcjapuwl7gfnzhzg6svtj0ph3gxu8kyuadudmf0kzsksqrfugfc"
            - name: ADMIN_SIGNING_KEY_FILE
              value: "/etc/secret/admin.sk"
          volumeMounts:
            - name: "data"
              mountPath: "/var/data"
            - name: "script"
              mountPath: "/etc/script"
            - name: "secret"
              mountPath: "/etc/secret"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: { pvc_name }
        - name: config
          configMap:
            name: hydra-pod-config
        - name: secret
          secret:
            secretName: hydra-pod-admin-key
        - name: socket
          emptyDir: {}
        - name: script
          configMap:
            name: open-head-script
