apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-head-volume
  namespace: hydra-doom
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp2
