---
apiVersion: batch/v1
kind: Job
metadata:
  name: publish-scripts
  namespace: hydra-doom
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: "socket"
          image: "ghcr.io/demeter-run/dmtrctl:sha-3ffefaa"
          restartPolicy: "Always"
          args:
            - "--project-id"
            - "b55545f5-31e7-4e6b-81d6-22f4e6b5a144"
            - "--api-key"
            - "{dmtr_api_key}"
            - "ports"
            - "tunnel"
            - "mainnet-mqgv9w"
            - "--socket"
            - "/ipc/socket"
          volumeMounts:
            - name: "socket"
              mountPath: "/ipc"
      containers:
        - name: "node"
          image: "{hydra-node-image}"
          restartPolicy: "Always"
          args:
            - "publish-scripts"
            - "--mainnet"
            - "--node-socket"
            - "/ipc/socket"
            - "--cardano-signing-key"
            - "/etc/secret/admin.sk"
          volumeMounts:
            - name: "secret"
              mountPath: "/etc/secret"
            - name: "socket"
              mountPath: "/ipc"
      volumes:
        - name: secret
          secret:
            secretName: hydra-pod-admin-key
        - name: socket
          emptyDir: {}
