name: Clippy

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/clippy.yml"
      - "crates/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/clippy.yml"
      - "crates/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clippy check lints
        run: cargo clippy -- -D warnings
