name: Global

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: choice
        required: false
        default: "false"
        options:
          - "true"
          - "false"

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_eks_cluster_arn: arn:aws:eks:us-east-1:509399595051:cluster/hydra-doom-dev-cluster
      TF_VAR_ssl_cert_arn: arn:aws:acm:us-east-1:509399595051:certificate/6ab8319d-1dec-494f-b71c-3a4132e42a5e

    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::509399595051:role/ClusterAdminRole
          role-session-name: Github-Actions
          role-duration-seconds: 1200

      - name: setup kubeconfig
        run: aws eks update-kubeconfig --name hydra-doom-dev-cluster

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: init terraform
        working-directory: playbook/cluster-setup
        run: terraform init

      - name: validate terraform
        working-directory: playbook/cluster-setup
        run: terraform validate

      - name: plan terraform
        working-directory: playbook/cluster-setup
        if: inputs.dry-run == 'true'
        run: terraform plan -input=false

      - name: apply terraform
        working-directory: playbook/cluster-setup
        if: inputs.dry-run == 'false'
        run: terraform apply -auto-approve -input=false
