name: Open Head

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/open-head.yml"
      - "src/**"

jobs:
  build-images:
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: .
            file: Dockerfile
            endpoint: cardano-scaling/open-head

    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ matrix.endpoint }},ghcr.io/${{ matrix.endpoint }}:${{ github.sha }}
          build-args:
          - BIN=open-head
